export const VENDORS = [
  'Sime Darby Property Bhd',
  'Tenaga Nasional Berhad',
  'DHL Express (Malaysia) Sdn Bhd',
  'Petronas Dagangan Berhad',
  'Telekom Malaysia Berhad',
  'Maybank Trustees Berhad',
  'Nippon Express (M) Sdn Bhd',
  'Selangor Human Resource Development Sdn Bhd',
  'Kumpulan Perangsang Selangor Berhad',
  'IBM Malaysia Sdn Bhd',
  'Microsoft Malaysia Sdn Bhd',
  'Schenker Logistics (Malaysia) Sdn Bhd',
  'Panasonic Appliances Refrigeration Devices (M) Sdn Bhd',
  'Shah Alam City Council (MBSA)',
  'Iron Mountain Malaysia Sdn Bhd',
  'Air Liquide Malaysia Sdn Bhd',
  'Pos Malaysia Berhad',
  'Securiforce Sdn Bhd',
  'Hitachi Systems Malaysia Sdn Bhd',
  'CBRE | WTW Malaysia Sdn Bhd',
  'ABC Freight Forwarders Sdn Bhd',
  'Oracle Corporation Malaysia Sdn Bhd',
  'FGV Holdings Berhad',
  'Bumi Armada Berhad',
  'Nestle (Malaysia) Berhad',
] as const;

export const TEXT_DESCRIPTIONS = [
  'Software license purchased for enterprise accounting system',
  'Electricity charges for Shah Alam plant - August billing cycle',
  'Freight forwarding charges for export shipment to Jakarta port',
  'IT equipment maintenance contract renewal for FY2026',
  'Legal consultation fees for cross-border compliance matter',
  'Office supplies and stationery for finance department Q3',
  'Annual insurance premium for factory equipment coverage',
  'Cloud infrastructure hosting fees - monthly subscription',
  'Repair and maintenance of production line machinery',
  'Consulting fees for tax advisory services rendered',
  'Telecommunications charges for corporate mobile plan',
  'Purchase of custom-built inventory management software',
  'Security services for factory premises - monthly contract',
  'Waste disposal and environmental compliance charges',
  'Training and development program for production staff',
  'Warehouse rental charges for overflow storage August',
  'Audit fees for statutory financial year-end review',
  'ICT hardware procurement - network switches and routers',
  'Provision for pending customer warranty claims Q3',
  'Provision for outstanding logistics invoices not yet received',
  'Custom software development for SAP integration module',
  'Employee relocation and travel reimbursement expenses',
  'Bank charges and transaction processing fees',
  'Marketing and promotional materials printing costs',
  'Utility charges - water supply for manufacturing facility',
  'ICT license renewal for enterprise security suite',
  'Machinery calibration and certification services',
  'Freight and logistics charges via NLS - inbound shipment',
  'Provision for year-end bonus accrual - Finance dept',
  'Purchase of custom software for quality control automation',
] as const;

export const PROFIT_CENTERS = [
  'PC-1001-FIN',
  'PC-1002-OPS',
  'PC-1003-LOG',
  'PC-1004-ICT',
  'PC-1005-PRD',
  'PC-1006-HR',
  'PC-1007-QA',
  'PC-1008-ADM',
] as const;

export const REASONING_TEMPLATES = [
  'Vendor and keyword match against master list indicate a recurring operational expense; classified as Revenue Expenditure based on transaction nature and amount threshold.',
  'Transaction text references capital equipment acquisition; matched against IRB Capital Allowance guidelines for 14% category based on asset class.',
  'Description matches known ICT hardware/software procurement pattern; classified under ICT 20% per Panasonic category rules.',
  'Amount and vendor match the Provision file entry; auto-classified as Provision ahead of general tax logic.',
  'Custom software development scope identified from transaction text; matched to Custom Software 20% capital allowance category.',
  'Vendor keyword match was ambiguous due to truncated description; low-confidence Revenue Expenditure suggestion pending manual review.',
  'Transaction pattern consistent with non-qualifying entertainment/donation expense per IRB guidelines.',
  'Asset class and amount indicate standard plant/machinery classification; AA 10% applied per capital allowance schedule.',
] as const;
